package com.example.entitiy;

import java.io.Serializable;

public class Test implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.xx
     *
     * @mbggenerated
     */
    private String xx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.aa
     *
     * @mbggenerated
     */
    private String aa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.xx
     *
     * @return the value of test.xx
     *
     * @mbggenerated
     */
    public String getXx() {
        return xx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.xx
     *
     * @param xx the value for test.xx
     *
     * @mbggenerated
     */
    public void setXx(String xx) {
        this.xx = xx == null ? null : xx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.aa
     *
     * @return the value of test.aa
     *
     * @mbggenerated
     */
    public String getAa() {
        return aa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.aa
     *
     * @param aa the value for test.aa
     *
     * @mbggenerated
     */
    public void setAa(String aa) {
        this.aa = aa == null ? null : aa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", xx=").append(xx);
        sb.append(", aa=").append(aa);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}